--DATA CLEANING, REMOVING AND UPDATED NULL OR EMPTY DATA FROM CUSTOMER_ORDERS_TABLE
SELECT *
FROM CUSTOMER_ORDERS
WHERE EXCLUSIONS = 'NULL'

SELECT *
FROM CUSTOMER_ORDERS
WHERE EXCLUSIONS = ' '

SELECT *
FROM CUSTOMER_ORDERS
WHERE EXTRAS = 'NULL'

SELECT *
FROM CUSTOMER_ORDERS
WHERE EXTRAS IS NULL

SELECT *
FROM CUSTOMER_ORDERS
WHERE EXTRAS = ' '

UPDATE CUSTOMER_ORDERS
SET EXCLUSIONS = 0
WHERE EXCLUSIONS = 'NULL'

UPDATE CUSTOMER_ORDERS
SET EXCLUSIONS = 0
WHERE EXCLUSIONS = ' '

UPDATE CUSTOMER_ORDERS
SET EXTRAS = 0
WHERE EXTRAS = 'NULL'


UPDATE CUSTOMER_ORDERS
SET EXTRAS = 0
WHERE EXTRAS IS NULL

UPDATE CUSTOMER_ORDERS
SET EXTRAS = 0
WHERE EXTRAS = ' '

SELECT *
FROM CUSTOMER_ORDERS;
