--DATA CLEANING, REMOVING AND UPDATED NULL OR EMPTY DATA FROM CUSTOMER_ORDERS_TABLE
SELECT *
FROM CUSTOMER_ORDERS
WHERE EXCLUSIONS = 'NULL'

SELECT *
FROM CUSTOMER_ORDERS
WHERE EXCLUSIONS = ' '

SELECT *
FROM CUSTOMER_ORDERS
WHERE EXTRAS = 'NULL'

SELECT *
FROM CUSTOMER_ORDERS
WHERE EXTRAS IS NULL

SELECT *
FROM CUSTOMER_ORDERS
WHERE EXTRAS = ' '

UPDATE CUSTOMER_ORDERS
SET EXCLUSIONS = 0
WHERE EXCLUSIONS = 'NULL'

UPDATE CUSTOMER_ORDERS
SET EXCLUSIONS = 0
WHERE EXCLUSIONS = ' '

UPDATE CUSTOMER_ORDERS
SET EXTRAS = 0
WHERE EXTRAS = 'NULL'


UPDATE CUSTOMER_ORDERS
SET EXTRAS = 0
WHERE EXTRAS IS NULL

UPDATE CUSTOMER_ORDERS
SET EXTRAS = 0
WHERE EXTRAS = ' '

--NOW, I VERIFY THERE'S NO EMPTY, NULL OR NAN VALUE. AS THIS IS SMALL DATASET, I DON'T NEET TO INCLUDE A WHERE CLAUSE.
SELECT *
FROM CUSTOMER_ORDERS;
